yolo_model:
  config_file:
    name: yolo-door.cfg
  weight_file:
    name: yolo-door.weights
  threshold:
    value: 0.3
  detection_classes:
    names:
      - door
      - handle
      - cabinet door
      - refrigerator door
